# Generated by Django 2.2.7 on 2020-01-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0002_auto_20200103_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='main_word',
            new_name='word',
        ),
    ]
