# Generated by Django 2.2.7 on 2020-05-02 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0004_auto_20200206_0701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='special_mark',
            new_name='category',
        ),
    ]
