# Generated by Django 2.2.7 on 2020-05-02 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0006_word_other_forms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='other_forms',
        ),
    ]
