# Generated by Django 2.2.7 on 2021-10-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0009_word_to_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=500)),
                ('paragraph', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
    ]
