# Generated by Django 2.2.7 on 2020-01-03 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='word',
            new_name='main_word',
        ),
    ]
