# Generated by Django 2.2.7 on 2020-02-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0003_auto_20200103_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='additional',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='example',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='special_mark',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
