# Generated by Django 2.2.7 on 2020-05-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0005_auto_20200502_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='other_forms',
            field=models.CharField(default='val', max_length=200),
            preserve_default=False,
        ),
    ]
