# Generated by Django 2.2.7 on 2021-11-11 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0012_auto_20211109_2227'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wordtraining',
            table='WordTraining',
        ),
    ]
