# Generated by Django 2.2.7 on 2021-11-20 05:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0017_userlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 20, 8, 10, 7, 988620), editable=False),
        ),
        migrations.CreateModel(
            name='WordPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_app.Word')),
            ],
        ),
    ]
