# Generated by Django 2.2.7 on 2021-11-20 17:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0019_auto_20211120_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='userlog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 20, 20, 51, 50, 414883), editable=False),
        ),
        migrations.CreateModel(
            name='GrammarRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=200)),
                ('example', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_app.GrammarSection')),
            ],
        ),
    ]
