# Generated by Django 2.2.7 on 2021-11-26 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0020_auto_20211120_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 26, 21, 6, 55, 773082), editable=False),
        ),
    ]
